language: node_js
node_js:
- '9'
install:
- npm install
script:
- npm test
cache:
  directories:
  - node_modules
notifications:
  slack:
    secure: K8sxXb6iybxO8rF3p6bgjYXea9MNejRZ48B1j70RXYC7OIGvmvamwymjo1SBlMucJm3jGnh6M2pS9hgfO9Vf5+yHS4aF6GKyUldb/jKyEqBmFvgYmMeEhXTh9ISClAWriAEeM2owMFUIb0HEMpkQ+N+a/1LlDGoJ9LFoMzJ9E8i8dz0ftMiPILPjz+HhDQm3q2hljwYTrvrceqthAGoSGxaxFqqAia4hfmkajFKbpWMkemFiymgjV+QKLbyRIAyL/sj1obDLmdBZlAdTSnzKYJBxAiX6VGb7qF3omLlFR0KG8KVvg5jpYgzCNXIMoCHMVKybmWDdH1iFkU/Wy0NP+im7r45R3pEOqiyfbWZsYtCh89IqgA8oqH6FIA80aWAMeLnBPAOr+qWkHdG/LFX1ZRD50/FQOJVkS57+kQTOuZGmy1W7LbAnrYrA1cRFpDblUmnbCFg5+p5fhbRjLWLfPCXRJ5QrQw5qlG4gnYrlmqOscpJduWq8jSnNbzA8v72rWMOD346phr0b7mnOGZZDIBMZHP+1bzEkaIMvPfSQi+SLRr0i+y6Umj4lrGIL8MnX3I5R+pJvHHeVAYjKJesKoCRghS7G18+iBHNp1K0AIhBfAGJsYiS4jLevLHL+CLoJpzlh6A9er0/i3HO/jbxAwF+SaMEs9ryiqc95OrCVNyQ=
