dist: trusty
sudo: true
services:
- docker
language: node_js
node_js:
- '7.3'
branches:
  only:
  - staging
  - /^v[0-9]+(\.[0-9]){0,2}$/
install:
- npm install
before_script:
- DOCKER_IMAGE_NAME="q-server"
- DOCKER_TAG=$TRAVIS_BRANCH
script:
- npm test
- docker build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG --build-arg APP_ENV=$TRAVIS_BRANCH .
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; docker tag $DOCKER_IMAGE_NAME:$DOCKER_TAG
  nzzonline/$DOCKER_IMAGE_NAME:$DOCKER_TAG; docker push nzzonline/$DOCKER_IMAGE_NAME:$DOCKER_TAG;
- if [ "$TRAVIS_BRANCH" == "staging" ]; then docker run --rm -it -e RANCHER_URL -e CATTLE_ACCESS_KEY
  -e CATTLE_SECRET_KEY etlweather/gaucho upgrade $RANCHER_SERVICE_ID_STAGING --auto_complete
  --start_first --imageUuid="docker:nzzonline/$DOCKER_IMAGE_NAME:$DOCKER_TAG" || true;
  fi
cache:
  directories:
  - node_modules
notifications:
  slack:
    secure: K8sxXb6iybxO8rF3p6bgjYXea9MNejRZ48B1j70RXYC7OIGvmvamwymjo1SBlMucJm3jGnh6M2pS9hgfO9Vf5+yHS4aF6GKyUldb/jKyEqBmFvgYmMeEhXTh9ISClAWriAEeM2owMFUIb0HEMpkQ+N+a/1LlDGoJ9LFoMzJ9E8i8dz0ftMiPILPjz+HhDQm3q2hljwYTrvrceqthAGoSGxaxFqqAia4hfmkajFKbpWMkemFiymgjV+QKLbyRIAyL/sj1obDLmdBZlAdTSnzKYJBxAiX6VGb7qF3omLlFR0KG8KVvg5jpYgzCNXIMoCHMVKybmWDdH1iFkU/Wy0NP+im7r45R3pEOqiyfbWZsYtCh89IqgA8oqH6FIA80aWAMeLnBPAOr+qWkHdG/LFX1ZRD50/FQOJVkS57+kQTOuZGmy1W7LbAnrYrA1cRFpDblUmnbCFg5+p5fhbRjLWLfPCXRJ5QrQw5qlG4gnYrlmqOscpJduWq8jSnNbzA8v72rWMOD346phr0b7mnOGZZDIBMZHP+1bzEkaIMvPfSQi+SLRr0i+y6Umj4lrGIL8MnX3I5R+pJvHHeVAYjKJesKoCRghS7G18+iBHNp1K0AIhBfAGJsYiS4jLevLHL+CLoJpzlh6A9er0/i3HO/jbxAwF+SaMEs9ryiqc95OrCVNyQ=
