dist: trusty
sudo: true
services:
  - docker

branches:
  only:
    - dev
before_script:
  - DOCKER_IMAGE_NAME="q-service"
  - DOCKER_TAG="dev"
  - if [ -n "TRAVIS_TAG"]; then 
      DOCKER_TAG=$TRAVIS_TAG;
    fi
script:
  - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG --build-arg APP_ENV=$TRAVIS_BRANCH . 
after_success:
  - if [ "$TRAVIS_BRANCH" == "dev" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker tag $DOCKER_IMAGE_NAME:$DOCKER_TAG nzzonline/$DOCKER_IMAGE_NAME:$DOCKER_TAG;
      docker push nzzonline/$DOCKER_IMAGE_NAME:$DOCKER_TAG;
      docker run --rm -it -e RANCHER_URL -e CATTLE_ACCESS_KEY -e CATTLE_SECRET_KEY etlweather/gaucho upgrade $RANCHER_SERVICE_ID --auto_complete --start_first --imageUuid="docker:nzzonline/$DOCKER_IMAGE_NAME:$DOCKER_TAG" || true;
    fi
  - 
